---
  - name: Install Metricbeat
    hosts: webservers
    become: true
    tasks:
    # Use command module
      - name: Download Metricbeat
        command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

    # Use command module
      - name: Install Metricbeat
        command: sudo dpkg -i metricbeat-7.6.1-amd64.deb

    # Use copy module
      - name: Metricbeat Config
        copy:
          src: /etc/ansible/metricbeat-config.yml
          dest: /etc/metricbeat/metricbeat.yml

    # Use command module
      - name: Enable and Configure Docker Module for Metricbeat
        command: metricbeat modules enable docker

    # Use command module
      - name: Setup Metricbeat
        command: metricbeat setup

    # Use command module
      - name: Start Metricbeat
        command: service metricbeat start

    # Use systemd module
      - name: Enable Metricbeat on Boot
        systemd:
          name: metricbeat
          enabled: yes